### ISSUE TITLE
LGTM seems to consider `size_t` to be the same as `uint64_t`

### ISSUE THREAD

**Issue by evverx** [lgtmhq/lgtm-queries#45]
LGTM reports a number of "self comparison" alerts such as https://lgtm.com/projects/g/systemd/systemd/snapshot/083df0e587c3d4f84dd4a748b05f89de93ba157c/files/src/core/dbus-socket.c?sort=name&dir=ASC&mode=heatmap&showExcluded=false#x5e69783004290b59:1.

Could it be that `convertedExprMightOverflow` doesn't expect that `size_t` can be 32 bits wide on 32-bit machines?

**Comment by jonas-semmle** [comment]
Yes, that's exactly the problem. The query only considers the architecture where the code was built.

**Comment by jonas-semmle** [comment]
I've made a fix for this problem we have under review now. Essentially, the fix suppresses the alert if there is any possibility that the cast might have an effect on a different platform.

I hope this fix, or a better one, will reach lgtm in less than a month from now. Things are moving slower than usual here due to summer holidays.

**Comment by evverx** [comment]
The alerts I pointed out seem to be gone. Thank you! I'm closing the issue.
